package com.athena.cases.features.exrt.enums;

public enum ExrtDisposition {
    ACCOUNT_NUMBER_UPDATED,
    ACCOUNT_NUMBER_UPDATED_AND_BILLING_REQUESTED,
    CANCELLED_PREVIOUSLY,
    COVERAGE_UPDATED,
    DIRECTLY_RESPONDED_TO_BY_CARRIER,
    FAX_MAIL_OVERNIGHT,
    NO_ACTION_WAS_DEEMED_NECESSARY,
    NO_RESPONSE_FROM_PI,
    PREPAY_PREMIUM_POSTED,
    PREPAY_REFUND_REQUESTED,
    REFUND_RECONCILED,
    REFUND_REISSUE_REQUESTED,
    REFUND_REQUESTED,
    REQUESTING_CLAIMS_FORMS,
    REQUESTING_CLAIMS_INFORMATION,
    REQUESTING_TO_CANCEL,
    RETURNED_TO_CONTACT_CENTER,
    SATISFACTORY_EXPLANATION_WAS_GIVEN_TO_THE_COMPLAINANT
}
